### ISSUE TITLE
broken on iOS 8.2

### ISSUE THREAD

**Issue by gaming-hacker** [haawa799/Metal-Flaps#1]
i try to compile and get following

ld: file not found:Metal-Flaps/DerivedData/Metal Flaps/Build/Products/Debug-iphoneos/MetalTryOut-Objc.app/MetalTryOut-Objc
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by haawa799** [comment]
Updated project for Xcode 6.3 and Swift 1.2
